/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ano-ui/components/AButton/AButton.vue')['AButton']
    ComponentA: typeof import('./src/components/ComponentA.vue')['default']
    ComponentAsync: typeof import('./src/components/ComponentAsync.vue')['default']
    ComponentB: typeof import('./src/components/ComponentB.vue')['default']
    ComponentC: typeof import('./src/components/component-c.vue')['default']
    ComponentD: typeof import('./src/components/ComponentD.vue')['default']
    Recursive: typeof import('./src/components/Recursive.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAttachments: typeof import('@tdesign/uniapp-chat/attachments/attachments.vue')['TAttachments']
    TButton: typeof import('@tdesign/uniapp/button/button.vue')['TButton']
    TChatLoading: typeof import('@tdesign/uniapp-chat/chat-loading/chat-loading.vue')['TChatLoading']
    TIcon: typeof import('@tdesign/uniapp/icon/icon.vue')['TIcon']
    TLoading: typeof import('@tdesign/uniapp/loading/loading.vue')['TLoading']
    TQrcode: typeof import('@tdesign/uniapp/qrcode/qrcode.vue')['TQrcode']
    TSkeleton: typeof import('@tdesign/uniapp/skeleton/skeleton.vue')['TSkeleton']
    UButton: typeof import('uview-pro/components/u-button/u-button.vue')['UButton']
    UniCalendar: typeof import('@dcloudio/uni-ui/lib/uni-calendar/uni-calendar.vue')['UniCalendar']
    UvButton: typeof import('@climblee/uv-ui/components/uv-button/uv-button.vue')['UvButton']
    UvIcon: typeof import('@climblee/uv-ui/components/uv-icon/uv-icon.vue')['UvIcon']
    UvLoadingIcon: typeof import('@climblee/uv-ui/components/uv-loading-icon/uv-loading-icon.vue')['UvLoadingIcon']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['WdButton']
  }
}
